name: Daily Inventory Update

on:
  schedule:
    # Run at 18:00 UTC (01:00 Bangkok time)
    - cron: "0 18 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-inventory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dotenv beautifulsoup4 openpyxl

      - name: Create data directory
        run: mkdir -p data

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Run inventory script
        run: python main.py

      - name: Upload inventory data
        uses: actions/upload-artifact@v3
        with:
          name: inventory-data
          path: |
            inventory_data.json
            data/

          - name: Commit and push if changes
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add inventory_data.json data/
            git commit -m "Update inventory data [skip ci]" || exit 0
            git push https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.gitit

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: execution-logs
          path: |
            *.log
