name: Daily Inventory Update

on:
  schedule:
    # Run at 18:00 UTC (01:00 Bangkok time)
    - cron: "0 18 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-inventory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dotenv beautifulsoup4 openpyxl

      - name: Create data directory
        run: mkdir -p data

      - name: Create .env file
        run: |
          echo "MY_USERNAME=${{ secrets.MY_USERNAME }}" >> .env
          echo "MY_PASSWORD=${{ secrets.MY_PASSWORD }}" >> .env
          echo "VEND_USERNAME=${{ secrets.VEND_USERNAME }}" >> .env
          echo "VEND_PASSWORD=${{ secrets.VEND_PASSWORD }}" >> .env
          echo "STORENAME=${{ secrets.STORENAME }}" >> .env
          echo "APIKEY=${{ secrets.APIKEY }}" >> .env
          echo "APISECRET=${{ secrets.APISECRET }}" >> .env
          echo "LINE_NOTIFY_TOKEN=${{ secrets.LINE_NOTIFY_TOKEN }}" >> .env

      - name: Run inventory script
        run: python main.py

      - name: Upload inventory data
        uses: actions/upload-artifact@v3
        with:
          name: inventory-data
          path: |
            inventory_data.json
            data/

      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add inventory_data.json data/
          git commit -m "Update inventory data [skip ci]" || exit 0
          git push

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: execution-logs
          path: |
            *.log
