name: Daily Inventory Update

on:
  schedule:
    # Run at 18:00 UTC (01:00 Bangkok time)
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    permissions:
      contents: write # เพิ่มสิทธิ์ในการเขียน repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dotenv beautifulsoup4 openpyxl pytz

      - name: Create data directory
        run: mkdir -p data

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Run inventory script
        run: python main.py

      - name: Upload inventory data
        uses: actions/upload-artifact@v4
        with:
          name: inventory-data
          path: |
            inventory_data.json
            data/
          retention-days: 5

      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add inventory_data.json data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update inventory data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }} # ใช้ GITHUB_TOKEN ที่มีมาให้

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-logs
          path: |
            *.log
